hw3: main.o Position.o Grid.o Goal.o Agent.o
	g++ -w -o hw3 main.o Position.o Grid.o Goal.o Agent.o
main.o: main.cpp
	g++ -w -c main.cpp
Position.o: Position.cpp
	g++ -w -c Position.cpp
Grid.o: Grid.cpp
	g++ -w -c Grid.cpp
Goal.o: Goal.cpp
	g++ -w -c Goal.cpp
Agent.o: Agent.cpp
	g++ -w -c Agent.cpp
clean:
	rm *.o hw3
