hw1: Card.o Deck.o Shoe.o main.o
	g++ -o hw1 Card.o Deck.o Shoe.o main.o
Card.o: Card.cpp
	g++ -c Card.cpp
Deck.o: Deck.cpp
	g++ -c Deck.cpp
Shoe.o: Shoe.cpp
	g++ -c Shoe.cpp
main.o: main.cpp
	g++ -c main.cpp
clean:
	rm *.o hw1
