hw2: main.o Agent.o Grid.o Goal.o Position.o
	g++ -o hw2 main.o Agent.o Grid.o Goal.o Position.o
main.o: main.cpp
	g++ -c main.cpp
Agent.o: Agent.cpp
	g++ -c Agent.cpp
Grid.o: Grid.cpp
	g++ -c Grid.cpp
Goal.o: Goal.cpp
	g++ -c Goal.cpp
Position.o: Position.cpp
	g++ -c Position.cpp
clean: 
	rm *.o hw2
